### ISSUE TITLE
Traffic Manager - problem on release of shaper/wred/threshold profile

### ISSUE THREAD

**Issue by jmmontenot** [OpenDataPlane/odp#1031]
Hello ODP team,

Destroy a shaper profile (same with wred and threshold profile) not release the profile (the profile keep reserved status).
After 128 profile creation and release, I have this error : ```odp_traffic_mngr.c:514:tm_common_profile_create():No free profiles left```

When tm create new shaper profile, the process search the first profile with a status = TM_STATUS_FREE and change it to TM_STATUS_RESERVED
(odp_tm_shaper_create > tm_common_profile_create > alloc_entry_in_tbl)

during destroy processus status of profile is unchanged (free process re tag to TM_STATUS_RESERVED !)
(odp_tm_shaper_destroy > tm_common_profile_destroy > free_tbl_entry)

extract of code odp_traffic_mngr.c line 323 (release 1.24.0.0)
```
static void free_tbl_entry(profile_tbl_t *profile_tbl,
			   profile_kind_t profile_kind,
			   uint32_t idx)
{
	switch (profile_kind) {
	case TM_SHAPER_PROFILE:
		odp_ticketlock_lock(&profile_tbl->shaper.lock);
		profile_tbl->shaper.profile[idx].status = TM_STATUS_RESERVED;
		odp_ticketlock_unlock(&profile_tbl->shaper.lock);
		return;

        ...
```

another question : why tm profiles are limited to 128 by type (shaper/wred/theeshold) ? I have a use case to create dynamically shaping queue and I can't exceed 128 shaper profile.

bests regards

**Comment by matiaselo** [comment]
Thanks for reporting this! I'll post a fix soon.

> another question : why tm profiles are limited to 128 by type (shaper/wred/theeshold) ? I have a use case to create dynamically shaping queue and I can't exceed 128 shaper profile.

I haven't written this code, but it seems the main reason was conserving memory. You should be able to safely increase these defines  in platform/linux-generic/odp_traffic_mngr.c:
```
#define MAX_SHAPER_PROFILES 128
#define MAX_SCHED_PROFILES 128
#define MAX_THRESHOLD_PROFILES 128
#define MAX_WRED_PROFILES 128
```
How many profiles would you require for your use case?

**Comment by jmmontenot** [comment]
Hello,

My use case is very specific, I use only shaper profile. Also, in this case, it's a waste to allocate memory for the another profiles.

One solution (improvment) could be a parameter value in `odp_tm_requirements_t`,  like recently `cache_size` with `odp_pool_param_t` (1.24.0.0) to manage the size of local pool memory

Best regards
