### ISSUE TITLE
Traffic Manager - Missing step during release of tm profile

### ISSUE THREAD

**Issue by jmmontenot** [OpenDataPlane/odp#1032]
Hello ODP team,

during release process of the tm profile (shaper / shed / wred / threshold), process check if the `ref_cnt` value from the profile params is != 0
extract odp_tm_shaper_destroy in odp_traffic_mngr.c line 3243 (1.24.0.0)
```
* Any locking required and validity checks must be done by the caller! */
static void tm_shaper_config_set(tm_system_t     *tm_system,
				 odp_tm_shaper_t  shaper_profile,
				 tm_shaper_obj_t *shaper_obj)
{
...
        if (profile_obj->ref_cnt != 0)
		return -1;
...
}
```

the problem, this value is increased during profile configuration (in `tm_shaper_config_set` for shaper configuration), but not one function in the release process allows to decrease this value. 

the workaround is before the call of `odp_tm_shaper_destroy` function, to call initial function to associate tm queue with a shaper profile and using a invalid profile : `odp_tm_queue_shaper_config(obj_queue_tm, ODP_TM_INVALID)`. 
this is the only way is to reexecute `tm_shaper_config_set` that remove old shaper params. 

```
/* Any locking required and validity checks must be done by the caller! */
static void tm_shaper_config_set(tm_system_t     *tm_system,
				 odp_tm_shaper_t  shaper_profile,
				 tm_shaper_obj_t *shaper_obj)
{
	tm_shaper_params_t *shaper_params;

	/* First remove any old shaper_params. */
	if (shaper_obj->shaper_params != NULL) {
		shaper_obj->shaper_params->ref_cnt--;
		shaper_obj->shaper_params = NULL;
	}
...
```

same with another profile : sched / wred and threshold.

best regards,

**Comment by matiaselo** [comment]
Hi,

At a glance this is how the API is supposed to work.
E.g. odp_tm_shaper_destroy():
```
 * It is an error if this shaper profile is still being
 * referenced by an active (connected) tm_node.
```
and from odp_tm_node_shaper_config()/odp_tm_queue_shaper_config()
```
 * Note that it is legal to specify ODP_TM_INVALID
 * indicating that this tm_queue no longer
 * implements a shaper function.
```

**Comment by jmmontenot** [comment]
thanks for the response, this point is not detailed in documentation (or I don't seen it). 

For additional information, i used `odp_tm_queue_disconnect` and `odp_tm_queue_destroy` before call the `odp_tm_shaper_destroy`. i thought that might be enough.

in resume, to destroy tm profile (shaper / shed / wred / threshold) assigned to a tm queue, 
the procedure is to remove the profile configuration on the tm queue (with `odp_tm_queue_shaper_config(obj_queue_tm, ODP_TM_INVALID)` ) before call the profile destroy function.

Best regards

**Comment by matiaselo** [comment]
> in resume, to destroy tm profile (shaper / shed / wred / threshold) assigned to a tm queue,
> the procedure is to remove the profile configuration on the tm queue (with `odp_tm_queue_shaper_config(obj_queue_tm, ODP_TM_INVALID)` ) before call the profile destroy function.

Yes, this is the current procedure. I'll close the ticket now but you can open it again if you have more questions.
