### ISSUE TITLE
ODP compilation failure with latest DPDK 20.11

### ISSUE THREAD

**Issue by priyanka-git-11** [OpenDataPlane/odp#1148]
Release Note dpdk 20.11: https://doc.dpdk.org/guides/rel_notes/release_20_11.html

STEPS Followed for building
--------------------------
1)DPDK
>>meson build
>>cd build
>>ninja
>>ninja install
>>ldconfig

2)ODP
#git branch
* master

# git log
commit 041cfc475dcd48de182e8225aaec76ed55257fd7 (HEAD -> master, origin/master,
origin/HEAD)
Merge: 11d3762e 5da36ba9
Author: Matias Elo <matias.elo@nokia.com>
Date:   Wed Dec 23 15:39:28 2020 +0200

   Merge pull request #112

   Merge and port odp-linux patches up to 12b675595

commit 5da36ba99b4cbab115fbc2d4b96391c05623be3e
Author: Matias Elo <matias.elo@nokia.com>
Date:   Mon Dec 7 16:25:21 2020 +0200

   validation: ipsec: fix termination when inline processing is not supported

   When inline IPsec processing is not supported, suite_context.pktio is set
   to ODP_PKTIO_INVALID by ipsec_suite_init(). Use odp_pktio_lookup() to get
   the loop pktio device handle during test termination to properly close the
   device.

   Signed-off-by: Matias Elo <matias.elo@nokia.com>
   Reviewed-by: Jere Leppänen <jere.leppanen@nokia.com>

#Steps for build
>>./bootstrap
>>./configure  --enable-debug --enable-debug-print  --prefix=$(pwd)/install
>> make -j${JOBS} install

ISSUE
--------------------

odp_buffer.c: In function ‘odp_buffer_snprint’:
odp_buffer.c:75:44: error: ‘struct rte_mbuf’ has no member named ‘buf_physaddr’; did
you mean ‘buf_addr’?
   "  phy_addr     %" PRIu64 "\n", hdr->mb.buf_physaddr);
                                           ^~~~~~~~~~~~
                                           buf_addr
Makefile:1435: recipe for target 'odp_buffer.lo' failed
make[2]: *** [odp_buffer.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/x86_64-linux-gnu/bits/_G_config.h:19:0,
                from /usr/include/x86_64-linux-gnu/bits/libio.h:35,
                from /usr/include/stdio.h:41,
                from /usr/local/include/rte_mempool.h:36,
                from /usr/local/include/rte_mbuf.h:38,
                from ../../platform/linux-
dpdk/include/odp/api/plat/packet_inlines.h:37,
                from odp_packet.c:9:
odp_packet.c:41:60: error: ‘struct rte_mbuf’ has no member named ‘userdata’; did you
mean ‘rearm_data’?
 .user_ptr         = offsetof(odp_packet_hdr_t, buf_hdr.mb.userdata),
                                                           ^
odp_packet.c: In function ‘_copy_head_metadata’:
odp_packet.c:310:9: error: ‘struct rte_mbuf’ has no member named ‘seqn’
 newhead->seqn = oldhead->seqn;
        ^~
odp_packet.c:310:25: error: ‘struct rte_mbuf’ has no member named ‘seqn’
 newhead->seqn = oldhead->seqn;
                        ^~
odp_packet.c:312:9: error: ‘struct rte_mbuf’ has no member named ‘udata64’
 newhead->udata64 = oldhead->udata64;
        ^~
odp_packet.c:312:28: error: ‘struct rte_mbuf’ has no member named ‘udata64’
 newhead->udata64 = oldhead->udata64;
                           ^~
odp_packet.c: In function ‘odp_packet_user_ptr_set’:
odp_packet.c:571:22: error: ‘struct rte_mbuf’ has no member named ‘userdata’; did you
mean ‘rearm_data’?
 pkt_hdr->buf_hdr.mb.userdata  = (void *)user_ptr;
                     ^~~~~~~~
                     rearm_data
odp_packet.c: In function ‘_odp_packet_copy_md_to_packet’:
odp_packet.c:1181:21: error: ‘struct rte_mbuf’ has no member named ‘userdata’; did you
mean ‘rearm_data’?
 dsthdr->buf_hdr.mb.userdata = srchdr->buf_hdr.mb.userdata;
                    ^~~~~~~~
                    rearm_data
odp_packet.c:1181:51: error: ‘struct rte_mbuf’ has no member named ‘userdata’; did you
mean ‘rearm_data’?
 dsthdr->buf_hdr.mb.userdata = srchdr->buf_hdr.mb.userdata;
                                                  ^~~~~~~~
                                                  rearm_data
Makefile:1435: recipe for target 'odp_packet.lo' failed
make[2]: *** [odp_packet.lo] Error 1
make[2]: Leaving directory '/root/GOPIKA_119_95/ofp/scripts/devbuild_ofp_odp_dpdk/odp-
dpdk/platform/linux-dpdk'
Makefile:1638: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/root/GOPIKA_119_95/ofp/scripts/devbuild_ofp_odp_dpdk/odp-
dpdk/platform/linux-dpdk'
Makefile:576: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by matiaselo** [comment]
Hi @priyanka-git-11, thanks for reporting this. Currently, the supported DPDK version are 18.11 and 19.11. Support for DPDK v20.11 is planned for late January / early February time frame. Please reopen this issue to https://github.com/OpenDataPlane/odp-dpdk/issues/, since this is related to ODP-DPDK implementation.

**Comment by matiaselo** [comment]
Issue moved to ODP-DPDK.
