### ISSUE TITLE
SIGSEGV from odp_event_type

### ISSUE THREAD

**Issue by jihyun1323** [OpenDataPlane/odp#1329]
sometime, i got a SIGSEGV from odp_event_type even if i already check event is ODP_EVNET_INVALID or not

Program terminated with signal SIGSEGV, Segmentation fault.
#0  odp_event_type (event=event@entry=0xffff03b59c00) at /SDK/SDK_OCTEON/OCTEONTX-SDK-6.3.0/odp-octeontx/platform/octeontx2/event.c:27
27	/SDK/SDK_OCTEON/OCTEONTX-SDK-6.3.0/odp-octeontx/platform/octeontx2/event.c: No such file or directory.
[Current thread is 1 (LWP 19166)]

back trace
Thread 1 (LWP 19166):
#0  odp_event_type (event=event@entry=0xffff03b59c00) at /SDK/SDK_OCTEON/OCTEONTX-SDK-6.3.0/odp-octeontx/platform/octeontx2/event.c:27
No locals.
#1  0x000000000050b328 in upal_handle_rx_packets (rxBuf=0xfffeee7fa348, rxBuf@entry=0xfffeee7fa3e8) at my_source_code.c:1295
        rx_queue = 0xffff91543200
        event = 0xffff03b59c00

upal_handle_rx_packets()
...
    odp_queue_t rx_queue = ODP_QUEUE_INVALID;
    odp_event_t event = odp_schedule(&rx_queue, ODP_SCHED_NO_WAIT);
    if (unlikely(event == ODP_EVENT_INVALID))
    {
        return UPAL_RX_PKT_INVALID;
    }

    switch (odp_event_type(event))
...

**Comment by JannePeltonen** [comment]
I am closing this issue as you seem to be using an ODP implementation that is not a part of this project. This project is only about the generic ODP API, API validation tests and the linux-generic implementation of the API. Issues in other ODP implementations are handled in their respective channels.
