### ISSUE TITLE
Missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [OpenDataPlane/odp#1457]
`return -1; ` should be `goto quit;`? Otherwise, the `file test_global.file = fopen(test_global.filename, "w");`  is not closed.
https://github.com/OpenDataPlane/odp/blob/2f16a667c8529fc77516b2dc848460ac8a720433/example/timer/odp_timer_accuracy.c#L740-L750

https://github.com/OpenDataPlane/odp/blob/2f16a667c8529fc77516b2dc848460ac8a720433/example/timer/odp_timer_accuracy.c#L720-L728

https://github.com/OpenDataPlane/odp/blob/2f16a667c8529fc77516b2dc848460ac8a720433/example/timer/odp_timer_accuracy.c#L791-L814

**Comment by MatiasElo** [comment]
Thanks for the report. PR #1461 fixes this issue.
