### ISSUE TITLE
Compiled failed with enable dpdk in v1.33.0.0

### ISSUE THREAD

**Issue by chrhong** [OpenDataPlane/odp#1458]
I update my dpdk release to v20.11 and odp version to v1.33.
The compile process refer the guide in DEPENDENCY file.
But I always compile failed while make:
```
# export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/workspace/dpdk/install/lib64/pkgconfig"
# ./bootstrap
# ./configure --enable-dpdk
# make -j
... 
 CCLD     ../../lib/libodp-linux.la
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find : No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [../../lib/libodp-linux.la] Error 1
make[2]: Leaving directory `/workspace/orgodp/platform/linux-generic'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/workspace/orgodp/platform/linux-generic'
make: *** [all-recursive] Error `1`
```

if I configure without dpdk, then make successfully!
Do you have the same issue ?

**Comment by chrhong** [comment]
@MatiasElo Did you test the latest release with DPDK v2011 ? Thanks.

**Comment by MatiasElo** [comment]
Hi,

> Did you test the latest release with DPDK v2011 ?

DPDK v20.11 is tested in the CI using Ubuntu 20.04, so this seems like a Red Hat specific issue.

For reference, here's my build procedure:
```
# DPDK (20.11.4-rc1)
cd <dpdk_dir>
meson build
cd build
meson configure -Dprefix=<dpdk_dir>/install
ninja
ninja install

# ODP (6ffd6a013c425930c5baf455a36aa44189555f7c)
./bootstrap
PKG_CONFIG_PATH=<dpdk_dir>/install/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH ./configure --enable-dpdk
make
```

Your DPDK install path looks different than mine. Have you checked that it's correct and you are not accidentally using DPDK library installed to system path?

Also, ODP configure output would be helpful for debugging.

**Comment by chrhong** [comment]
compiled with "--enable-dpdk-shared" successfully, thanks Matias. It already match my usage, I think the issue could be closed.
