### ISSUE TITLE
XDP  Cannot receive packets with 'direct mode' API

### ISSUE THREAD

**Issue by bogdanPricope** [OpenDataPlane/odp#1624]
The interface is configured like this:

	odp_pktio_param_init(&pktio_param);
	pktio_param.in_mode = ODP_PKTIN_MODE_DIRECT;
	pktio_param.out_mode = ODP_PKTOUT_MODE_DIRECT;

	odp_pktin_queue_param_init(&pktin_param);
	pktin_param.op_mode = ODP_PKTIO_OP_MT_UNSAFE;
	pktin_param.hash_enable = 1;
	pktin_param.hash_proto.proto.ipv4_udp = 1;
	pktin_param.hash_proto.proto.ipv4_tcp = 1;
	pktin_param.hash_proto.proto.ipv6_udp = 1;
	pktin_param.num_queues = rx_queues;

	odp_pktout_queue_param_init(&pktout_param);
	pktout_param.op_mode    = ODP_PKTIO_OP_MT_UNSAFE;
	pktout_param.num_queues = tx_queues;

No packets are received with odp_pktin_recv() API.

Also, should be a valid case to have different number of input and output queues. Actually, this is a common use-case for nfp/ofp performance tests:  one input queue per worker thread and one output queue per worker + control threads.

**Comment by TuomasTaipale** [comment]
Did you configure your network interface's combined-tx-rx queue count to match your worker count with `ethtool` as elaborated in `DEPENDENCIES`?

**Comment by bogdanPricope** [comment]
You mean:
ethtool -L ens5f0 combined 4
ethtool -L ens5f1 combined 4

With that I can receive packets but all packets are received on a single queue. I guess the RSS is no available.

Thread   Core               Rx               Tx      Tx_frag   Rx_IP_frag   Rx_IP_reas    Description

      7      1                0                0            0            0            0               
      8      3                0                0            0            0            0               
      9      2                0                0            0            0            0               
     10      4        150491820        150480385            0            0            0 

I see that you used ioctl(SIOCETHTOOL, ETHTOOL_GCHANNELS) to get the channels. Maybe you can also set the channels from code.

**Comment by bogdanPricope** [comment]
For the record, on IP fwd use-case, one queue, I am getting 2.52 mpps (vs. 3.2/3.9 mpps dpdk pktio). It sounds promising but it is sad that we cannot test with RSS and multiple queues.

**Comment by TuomasTaipale** [comment]
Above `ethtool` config: yes, correct. Configuring this programmatically was planned at first, however, this became a bit challenging to implement in a generic way as some NICs (Mellanox) handle the zero-copy queues quite differently. So, for now, this is to be done manually.

RSSing is carried out by whatever config `ethtool -x` shows (should change according to `ethtool -L` config) and there's multiqueue support and tput should scale quite linearly: In my environment I'm getting increase from ~6.8 Gbit/s to ~27.5 Gbit/s with `odp_l2fwd` with one to four workers (64 B frames). Proper scaling of course requires that packets are divided somewhat evenly between the created output queues.

**Comment by bogdanPricope** [comment]
Ok. I would have went with a generic implementation and some config or startup configuration flags for not-generic behaviors… but you know better your use-case/NICs constraints.

Thanks for this pktio and good luck further...
