### ISSUE TITLE
why odp_timer_current_tick returns ns rather than the curr_tick?

### ISSUE THREAD

**Issue by HsuJv** [OpenDataPlane/odp#1852]
Hi team,

I'm currently working on upgrading the ODP in my application from 1.21 to 1.40.
As mentioned in the title, I found that since ODP-1.23, the `odp_timer_current_tick` function changes its definition, along with other APIs like `odp_timer_tick_to_ns` & `odp_timer_ns_to_tick`
It doesn't make any sense to me that this API returns the nanoseconds since it is called ***curr_tick***.
And I can't find any description of this incompatible change in CHANGELOGS.
Since my app is using ticks as the minimum timer resolution, can any of you here kind advise which API to use to get the ***REAL*** tick? (Lots of my codes compare time duration with pre-defined ticks, and now it fails since I can get it only in nanoseconds but not ticks)

BRs

**Comment by psavol** [comment]
Hi,

As odp_timer_current_tick() specification states, a tick is implementation specific unit of time. Application should not assume that a tick is has a particular length in time, but use those ns_to_tick and tick_to_ns function to convert between tick and time in nanoseconds. When tick is abstract unit, an implementation may choose to do time calculations with high granularity (e.g.  use a nanosecond as tick) to minimize rounding errors. Timer resolution tells how much error to expect between the requested expiration time, and the time when the timeout is actually sent to the application (e.g. 1000 nsecs later than requested).

You may use odp_timer_pool_info() to check exact length of a tick. That information may help e.g. expiration time to ticks conversion with odd source clock / tick frequencies. 

/**
 * Current tick value
 *
 * Returns the current tick value of the timer pool. Timer tick is an implementation defined unit
 * of time. Timer tick value increments with a constant, timer pool specific frequency. Tick
 * frequency may be equal or higher than the requested timer pool resolution. The frequency can be
 * checked with odp_timer_pool_info(). Tick value increments with implementation specific step
 * sizes. The value will not wrap around in at least 10 years from the ODP instance startup.
 *
 * @param timer_pool  Timer pool
 *
 * @return Current time in timer ticks
 *
 * @see odp_timer_tick_info_t
 */
uint64_t odp_timer_current_tick(odp_timer_pool_t timer_pool);
