### ISSUE TITLE
Netmap zero-copy input is not supported

### ISSUE THREAD

**Issue by jmtilli** [OpenDataPlane/odp#559]
ODP does two memory-copies when used with netmap: memory copy from netmap input buffers to `odp_packet_t` buffers and memory copy from `odp_packet_t` buffers to netmap output buffers.

I asked the netmap developers whether freeing buffers in a different order than allocating them is supported, and yes it is: https://github.com/luigirizzo/netmap/issues/475

However, the input-side copy is unnecessary: ODP packets could perhaps refer directly to the netmap buffers. This requires one to manipulate `buf_idx` when returning buffers back to the kernel, and also possibly set `NS_BUF_CHANGED` if `buf_idx` changed. This might also require one to have two internal implementatons of `odp_packet_t` data types: ones that were allocated by receiving packets (and thus refer to netmap memory), and ones that were allocated entirely within userspace (and thus refer to separately allocated userspace memory). I guess with clever design, ODP API does not need to change, and the two internal implementations of `odp_packet_t` would be just an internal implementation detail.

I'll see if I have time to do a prototype of this in LDP (https://github.com/jmtilli/pptk/tree/master/ldp) which currently has zero-copy input but requires one to deallocate packets in the same order they were allocated.

One potential problem is that unlike with LDP where you have to specify an input queue when freeing packets, and the specified input queue will then get the freed packets, in ODP the `odp_packet_free` function does not take as a parameter an input queue. If the packet data structure is modified to hold a pointer to the input queue from which it was received, it is possible to have a pointer to the input queue, but then the thread freeing the packet may be different than the thread that received the packet, meaning a mutex lock is required for netmap input and also for freeing packets. So there may still be some roadblocks before this can be implemented. I initially designed LDP to interface to netmap as well as possible, so LDP doesn't have similar roadblocks.

@matiaselo, as the implementer of the netmap pktio, take a note of this issue. I guess the zero-copy input could improve ODP performance much, especially with VALE, perhaps close to the levels offered by LDP.

**Comment by Bill-Fischofer-Linaro** [comment]
We should take this into consideration when integrating `net_mdev` support into the ODP mainline. It's currently part of the old Caterpillar development branch. @apalos and @MykytaI may have additional comments on this.

**Comment by matiaselo** [comment]
As you have noted it is possible to remove the packet copy when receiving packets from netmap devices. However, implementing this is not trivial and would likely require at least minor API changes.

Currently, the packet pool is passed as an argument to odp_pktio_open(). When using netmap buffers directly, one option would be to pass pool parameters to pktio_open() -> pktio specific pool capability function would also be needed (e.g. odp_pktio_pool_capability()). From implementation point of view the complexity comes from the packet API functions, many of which would have to be modified to operate correctly with netmap buffers (have  no headroom etc.).

From ODP point of view the simplest method for zero-copy netmap operation would be if it would be possible to replace the netmap buffer data area with ODP packet buffers. This is how zero-copy dpdk pktio is implemented.

**Comment by Bill-Fischofer-Linaro** [comment]
@matiaselo ODP now supports configurable headroom in pools and so pools with a default headroom of zero should be no problem. Or are you suggesting that ODP segment manipulation APIs, _e.g.,_  `odp_packet_extend_head()`, would be problematic with netmap zero-copy?

**Comment by matiaselo** [comment]
We would likely need to support capabilities for pktio specific pools to not unnecessarily limit the capabilities of generic packet pool. Headroom was an example of such limitation.

Yes, I was mainly thinking about the packet manipulation functions such as odp_packet_extend_tail() or odp_packet_concat(). Looking at the code, one way to avoid complexity initially would be to fall back using generic packets buffers when doing packet manipulations requiring allocation of new packets.

**Comment by apalos** [comment]
@Bill-Fischofer-Linaro we haven't done any steps towards zero copy yet as we had to resolve some iommu issues and buffer allocation from user-space. We'll keep an eye on the conversation though in case remarks ring a bell
