### ISSUE TITLE
TCP transmission failed to send packets

### ISSUE THREAD

**Issue by bestgen** [OpenDataPlane/odp#772]
I built a simple three-point network to use odp&ofp (both are master version) to forward packets. The central point runs ofp&odp as a router, and the other two runs iperf as client and server, without odp$ofp.
UDP transmission is good. When using iperf through ofp & odp to transmit TCP packets, the client can only send several packets after connection established and then it nearly failed to continue. The speed is very slow.
I use wireshark to capture the packets and do some tests, and find:
1. If TCP packets is larger than the MSS(1460 Bytes), it will trigger TCP retransmission. Each time the ACK from server expects a 1448 length increasing, while the packet length from the client increasing fast. After several packets, TCP flow will be out of order. In other words, the ACK from receiver limits the TCP packets increasing and leads to transmission fail.  
2. If I set TCP packets no larger than MSS, the receiving port can receive expected packets, but the packets captured from transmitting port are still larger than MSS. It seems very possible that the ODP or OFP reassemble the packets. (wireshark shows IPv4 fragmentation flag is not set)

Is there anyone have some ideas about this problem, or have got similar situation before?
Thanks.

**Comment by matiaselo** [comment]
This issue was marked as solved in OFP (https://github.com/OpenFastPath/ofp/issues/219), so can it be closed also here? You can increase interface MTU with normal Linux system tools (e.g. `ifconfig`).
