### ISSUE TITLE
bus error

### ISSUE THREAD

**Issue by ieliynehc** [OpenDataPlane/odp#784]
Sometimes, when my ODP application exits and restarts it, it will encounter bus error. As long as this phenomenon occurs, it will not disappear unless the Linux OS is restarted. If the Linux OS is not restarted, the bus error will appear every time the application is started.

Although restarting Linux OS can temporarily avoid this problem, after a few days, it will appear again.

Can I get any help from here? Thank you.

Linux CentOS  3.10.0-514-el7.x86_64
![image](https://user-images.githubusercontent.com/42364321/50805682-80182480-132e-11e9-864e-b3121efa7e75.png)

**Comment by Bill-Fischofer-Linaro** [comment]
What level of ODP are you using? And what compiler (version and release) are you using to compile it and your application?

**Comment by matiaselo** [comment]
Hi,

Are you running ODP natively on CentOS or inside a container? How about huge pages?

You could build ODP with `--enable-debug` and `--enable-debug-print` flags to get more information. Are you checking pool capability (`odp_pool_capability()`) and using valid parameters for `odp_pool_create()`?

**Comment by muvarov** [comment]
do you run this under docker (if yes, you have to increase shm size). More likely you have out of memory error.
