### ISSUE TITLE
API doc links are not working

### ISSUE THREAD

**Issue by mvl-skardach** [OpenDataPlane/odp#827]
Dear ODP maintainers,

It looks like the API documentation links are not operational post migration. I
mean the links on https://opendataplane.org/index.php/service/documentation/.

https://opendataplane.github.io/odp/ - works fine
https://odp.openfastpath.org/api-documentation/v1.21.0.0/ - 404 :(
http://odp.openfastpath.org/api-documentation/v1.17.0.0/ - 404 :(

**Comment by matiaselo** [comment]
Thanks for reporting this. The links are now fixed.
