### ISSUE TITLE
SIGSEGV: example/sysinfo (raspberry Pi 3B+, arm7, odp-linux, gcc 8.2.0)

### ISSUE THREAD

**Issue by peterlauro** [OpenDataPlane/odp#915]
ODP compiled on raspberry Pi 3 B+; gnu gcc 8.2.0; rasbian 32 bits;

the reason of sigsegv: the usage of printf formater "lu" on type uint64_t instead of "llu"
in odp_ishm.c; function int _odp_ishm_term_local(void): lines 2040, 2052 and 2055.

odp configuration:
[config_odp.txt](https://github.com/OpenDataPlane/odp/files/4054485/config_odp.txt)

run of example/sysinfo/odp_sysinfo
[segmentation_sysinfo.txt]
(https://github.com/OpenDataPlane/odp/files/4054492/segmentation_sysinfo.txt)

gdb output:
[gdb_sysinfo.txt](https://github.com/OpenDataPlane/odp/files/4054490/gdb_sysinfo.txt)

suggested solution:
[odp_ishm.c.txt](https://github.com/OpenDataPlane/odp/files/4054523/odp_ishm.c.txt)

**Comment by matiaselo** [comment]
Thanks for an excellent bug report! I'll make a PR to fix this.

**Comment by matiaselo** [comment]
@peterlauro I posted a PR which should fix this problem. Could you please verify that the fix works also for you.

If you wish to share your name and email address I can tag you in the fix commit.

**Comment by peterlauro** [comment]
@matiaselo 
Thanks, I will verify the PR today evening.

Name: Peter Lauro
Email: lauro_konik@hotmail.com

BR,

**Comment by peterlauro** [comment]
with the posted PR, the sysinfo example works on my configuration (Rapberry Pi 3B+).
[odp_sysinfo.log](https://github.com/OpenDataPlane/odp/files/4062203/odp_sysinfo.log)

**Comment by matiaselo** [comment]
> with the posted PR, the sysinfo example works on my configuration (Rapberry Pi 3B+).
> [odp_sysinfo.log](https://github.com/OpenDataPlane/odp/files/4062203/odp_sysinfo.log)

Thanks, I'll merge the patches once the validation tests pass.
